version: '3.9'

services:
  dev-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: password_dev
      POSTGRES_DB: db_dev
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data